account/urls.py
"""
URLconf for registration and activation, using django-registration's
default backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.default.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead.

"""

from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView
from account.views import activate, register

urlpatterns = patterns('',
                       url(r'^post/$', 'conversation.views.post'),
                       url(r'^comment/$', 'conversation.views.comment'),
                       url(r'^deleteComment/$', 'conversation.views.deleteComment'),
                       url(r'^deletePost/$', 'conversation.views.deletePost'),
                       url(r'^endorse/$', 'endorsements.views.endorse'),
                       url(r'^account/login/$', 'account.views.login'),
                       url(r'^logout/$', 'account.views.logout'),
                       url(r'^(?P<username>[\w\.\-]+)$', 'account.views.profile'),
                       url(r'^(?P<username>[\w\.\-]+)/connect/$', 'connections.views.connect'),
                       url(r'^(?P<username>[\w\.\-]+)/info/$', 'account.views.profile_info'),
                       url(r'^(?P<username>[\w\.\-]+)/connections/$', 'account.views.profile_connections'),
                       url(r'^(?P<username>[\w\.\-]+)/courses/$', 'account.views.profile_courses'),
                       url(r'^activate/complete/$',
                           TemplateView.as_view(template_name='templates/activation_complete.html'),
                           name='registration_activation_complete'),
                       # Activation keys get matched by \w+ instead of the more specific
                       # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                       # that way it can return a sensible "invalid key" message instead of a
                       # confusing 404.
                       url(r'^activate/(?P<activation_key>\w+)/$',
                           activate,
                           name='registration_activate'),
                       url(r'^register/$',
                           register,
                           name='registration_register'),
                       url(r'^register/complete/$',
                           TemplateView.as_view(template_name='templates/registration_complete.html'),
                           name='registration_complete'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='templates/registration_closed.html'),
                           name='registration_disallowed'),
                       (r'^activate/$', 'account.views.activate'),
                       )

documents/urls.py
from django.conf.urls import patterns, url

# All urls are subject to change once the course identification system is up.
urlpatterns = patterns('',
                       url(r'^documents/$', 'documents.views.documents'),
                       url(r'^documents/filter/(?P<course_id>\w+)/$', 'documents.views.documents'),
                       url(r'^upload/$', 'documents.views.upload'),
                       url(r'^renameDocument/$', 'documents.views.rename_document'),
                       url(r'^deleteDocument/$', 'documents.views.delete_document'),
                       url(r'^documents/(?P<file_id>\w+)/$', 'documents.views.download'),
                       )

account/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from page.models import Page
from conversation.models import ConvoWall
from messages.models import Inbox


def getPath(instance, filename):
    path = 'user_' + str(instance.id) + '/' + filename
    return path


class UserProfile(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('T', 'Transgender'),
        ('E', 'Extraterrestrial'),
        ('O', 'Other'),
    )
    user = models.ForeignKey(User, unique=True)
    wall = models.ForeignKey(ConvoWall, unique=True, related_name='Wall')
    messages = models.ForeignKey(Inbox, unique=True, related_name='Messages')
    image = models.ImageField(upload_to=getPath)
    birthday = models.DateField(blank=True, null=True, name="birthday")
    education = models.CharField(max_length=100)
    major = models.CharField(max_length=50, default="Undeclared")
    tagline = models.CharField(blank=True, max_length=200)
    phone_number = models.CharField(blank=True, max_length=12)
    about = models.CharField(max_length=1000, blank=True)
    interests = models.CharField(max_length=1000, blank=True)
    school = models.ForeignKey(Page, related_name='School')
    sex = models.CharField(max_length=1, choices=GENDER_CHOICES, default='E')
    modified = models.DateTimeField(auto_now=True)
    first_time = models.BooleanField(default=True)
    connection_request_email = models.BooleanField(default=True)
    endorsement_email = models.BooleanField(default=True)
    profile_post_email = models.BooleanField(default=True)
    course_post_email = models.BooleanField(default=True)
    new_course_member_email = models.BooleanField(default=True)

    def getImage(self):
        if self.image:
            return self.image.url
        else:
            char = self.user.last_name[-1]
            num = str((ord(char) % 26) + 1)
            if len(num) == 1:
                num = '0' + num
            return '%simg/cats/00' % settings.STATIC_URL + num + '.jpg'


def getSchool(self):
    virginia_tech = Page.objects.get(title='Virginia Tech')
    jmu = Page.objects.get(title='James Madison University')
    uva = Page.objects.get(title='University of Virginia')
    konkourse = Page.objects.get(title='Konkourse')
    emailLookup = {
        'vt.edu': virginia_tech,
        'jmu.edu': jmu,
        'dukes.jmu.edu': jmu,
        'virginia.edu': uva,
        'konkourse.com': konkourse,
    }
    parts = self.split('@')
    school = emailLookup[parts[1]]
    return school


def send_endorsement_email(endorser_name, endorsee_name, endorsee_email):
    from templated_email import send_templated_mail
    send_templated_mail(
        template_name='new_endorsement',
        from_email='admin@konkourse.com',
        recipient_list=[endorsee_email],
        context={
            'endorser_name': endorser_name,
            'endorsee_name': endorsee_name,
        },
        # Optional:
        # cc=['cc@example.com'],
        # bcc=['bcc@example.com'],
        # headers={'My-Custom-Header':'Custom Value'},
        # template_prefix="my_emails/",
        # template_suffix="email",
    )

messages/models.py
from django.db import models
from account.models import User


class Message(models.Model):
    sender = models.ForeignKey(User, related_name='message_sender')
    recipient = models.ManyToManyField(User, related_name='message_recipients')
    created = models.DateTimeField(auto_now_add=True)
    message = models.TextField(default="")
    header = models.CharField(max_length=180, default="")
    deleted = models.BooleanField(default=False)


class MessageChain(models.Model):
    messages = models.ManyToManyField(Message)
    new_message = models.BooleanField(default=True)
    deleted = models.BooleanField(default=False)


class Inbox(models.Model):
    chains = models.ManyToManyField(MessageChain)
    owner = models.ForeignKey(User)

courses/forms.py
from django import forms
from courses.models import Course
from django.core.files.uploadedfile import InMemoryUploadedFile


class CourseInitialForm(forms.Form):
    course_number = forms.CharField(max_length='10',
                                    widget=forms.TextInput(attrs={'placeholder': ''}))
    course_id = forms.CharField(max_length='10',
                                widget=forms.TextInput(attrs={'placeholder': ''}))


class CourseForm(forms.ModelForm):
    CREDIT_OPTIONS = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )
    SEMESTER_OPTIONS = (
        ('S013', 'Spring 2013'),
        ('M113', 'Summer I 2013'),
        ('M213', 'Summer II 2013'),
        ('F013', 'Fall 2013'),
        ('S014', 'Spring 2014'),
    )
    time_formats = ['%H:%M', '%I:%M%p', '%I:%M %p']

    class Meta:
        model = Course

        exclude = ('tag',
                   'number',
                   'course_id',
                   'course_users',
                   'institution',
                   'events',
                   'wall')

    image = forms.ImageField(required=False, widget=forms.FileInput)
    name = forms.CharField(max_length=42,
                           required=False)
    name.widget.attrs['class'] = 'span4'
    professor = forms.CharField(max_length=52,
                                required=False)
    professor.widget.attrs['class'] = 'span4'
    semester = forms.ChoiceField(choices=SEMESTER_OPTIONS,
                                 required=False)
    semester.widget.attrs['class'] = 'span4'
    time = forms.TimeField(input_formats=time_formats,
                           required=False,
                           widget=forms.TimeInput(format='%I:%M %p'))
    time.widget.attrs['class'] = ''
    credits = forms.ChoiceField(choices=CREDIT_OPTIONS,
                                required=False)
    credits.widget.attrs['class'] = 'span4'
    about = forms.CharField(max_length=125, widget=forms.Textarea,
                            help_text='125 characters max, try something short and sweet.',
                            required=False)
    about.widget.attrs['class'] = 'span4'

    def clean_image(self):
        image = self.cleaned_data['image']
        if image is not None:
            if isinstance(image, InMemoryUploadedFile) and image._size > 10 * 1024 * 1024:
                raise forms.ValidationError("File size is too big.")
        # Always return the cleaned data, whether you have changed it or
        # not.
        return image

documents/views.py
from django.shortcuts import redirect
from django.template import RequestContext
from django.http import HttpResponse
from django.shortcuts import render
from documents.models import Document
import os
import mimetypes
from documents.forms import DocumentForm
from django.core.context_processors import csrf
from django.utils import simplejson
from django.conf import settings
from conversation.models import ConversationPost
from courses.models import Course


def download(request, file_id):
    doc = Document.objects.get(id=file_id)
    file = open(settings.MEDIA_ROOT + doc.file.name, "r")
    mimetype = mimetypes.guess_type(doc.file.name)[0]
    if not mimetype:
        mimetype = "application/octet-stream"

    response = HttpResponse(file.read(), mimetype=mimetype)
    response["Content-Disposition"] = "attachment; filename=%s" % doc.filename
    return response


def documents(request, course_id=-1):
    if (request.user.is_authenticated() and request.user.is_active):
        u = request.user
        courses = Course.objects.filter(course_users=u)
        if course_id < 0:
            documents = Document.objects.filter(course__in=courses)
        else:
            documents = Document.objects.filter(course__id=course_id)
        variables_for_template = {
            'name': u.first_name + ' ' + u.last_name,
            'username': request.user.username,
            'form': DocumentForm(),
            'documents': documents,
            'courses': courses,
            'course_id': course_id,
        }
        variables_for_template.update(csrf(request))
        return render(request, 'website/documents.html', variables_for_template,
                      context_instance=RequestContext(request))
    else:
        return redirect("/")


def upload(request):
    if request.method == 'POST':
        doc = __upload_core(request)
    else:
        redirect("/")
    if isinstance(doc, Exception):
        return Exception()
        u = request.user
        name = u.first_name + ' ' + u.last_name
        username = request.user.username
        variables_for_template = {
            'name': name,
            'username': username,
        }
        return redirect('/documents/', variables_for_template)
    else:
        return Exception()


def __upload_core(request):
    form = DocumentForm(request.POST, request.FILES)
    if form.is_valid():
        u = request.user
        doc = Document(owner=u)
        file = request.FILES['file']
        doc.filename = request.FILES['file'].name
        doc.save()
        doc.file.save('file_' + str(doc.id), file)
        return doc
    else:
        return Exception()


def _uploadDocument(doc, file):
    with open(settings.MEDIA_ROOT + '/' + doc.owner.username + '/file_' + str(doc.id), 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)
    destination = File(destination)
    return destination


def delete_document(request):
    results = {'success': False}
    if request.user.is_authenticated() and request.user.is_active:
        if request.method == 'POST':
            POST = request.POST
            doc = Document.objects.get(id=POST['id'])
            if doc.owner != request.user:
                results = {'success': False}
                json = simplejson.dumps(results)
                return HttpResponse(json, mimetype='application/json')
            post = None
            # If a document was uploaded through a post, delete that post as well.
            try:
                post = ConversationPost.objects.get(document=doc)
            except:
                pass
            if post:
                post.deleted = True
                post.save()
            doc.deleted = True
            os.remove(settings.MEDIA_ROOT + doc.file.name)
            doc.save()
            results = {'success': True}
    json = simplejson.dumps(results)
    return HttpResponse(json, mimetype='application/json')


def rename_document(request):
    results = {'success': False}
    if request.user.is_authenticated() and request.user.is_active:
        if request.method == 'POST':
            POST = request.POST
            doc = Document.objects.get(id=POST['id'])
            doc.filename = POST['newName']
            doc.save()
            results = {'success': True}
    json = simplejson.dumps(results)
    return HttpResponse(json, mimetype='application/json')

messages/views.py
# Create your views here.
from django.http import HttpResponse
from django.template import loader
from django.template.context import Context
from django.template import RequestContext
from django.shortcuts import redirect
from django.shortcuts import render
from conversation.models import ConvoWall, ConversationPost


def messages(request):
    if request.user.is_authenticated():
        first_name = request.user.first_name
        last_name = request.user.last_name
        username = request.user.username
        messageWall = request.user.get_profile().messages
        messages = ConversationPost.objects.filter(wall=request.user.get_profile().messages)

        variables_for_template = {
            'first_name': first_name,
            'last_name': last_name,
            'username': username,
            'messages': messages,
            'messageWall': messageWall,
        }
        return render(request, 'website/messages.html', variables_for_template,
                      context_instance=RequestContext(request))


def messages_compose(request):
    if request.user.is_authenticated():
        first_name = request.user.first_name
        last_name = request.user.last_name
        username = request.user.username
        messageWall = request.user.get_profile().messages
        messages = ConversationPost.objects.filter(wall=request.user.get_profile().messages)

        variables_for_template = {
            'first_name': first_name,
            'last_name': last_name,
            'username': username,
            'messages': messages,
            'messageWall': messageWall,
        }
        return render(request, 'website/messages_compose.html', variables_for_template,
                      context_instance=RequestContext(request))


def messages_view(request):
    if request.user.is_authenticated():
        first_name = request.user.first_name
        last_name = request.user.last_name
        username = request.user.username
        messageWall = request.user.get_profile().messages
        messages = ConversationPost.objects.filter(wall=request.user.get_profile().messages)

        variables_for_template = {
            'first_name': first_name,
            'last_name': last_name,
            'username': username,
            'messages': messages,
            'messageWall': messageWall,
        }
        return render(request, 'website/messages_view.html', variables_for_template,
                      context_instance=RequestContext(request))

templates/website/accountsettings_security.html
{% extends "base.html" %}
{% load static%}
{% block includes %}{{ block.super }}
{% endblock includes %}
{% block style %}
<style type="text/css">
.form-horizontal .control-label {
	width:150px;
	}
.form-horizontal .controls {
	margin-left:170px;
	}
.checkbox_class {
    float:left;
}
</style>
{% endblock style %}
{% block script %}
<script>
$(function(){
	$('#dp1').datepicker();
});
</script>
{% endblock script %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
	<div class="row">
    	<div class="span12">
        	<h4 style="margin-top:30px; margin-left:20px; color:#da4f49;"><i class="icon-cogs"></i> Settings</h4>
        	<hr style="margin-bottom:40px;" />
        </div>
    </div>
	<div class="row">
    	<div class="span12">
        	<div class="row">
            	<div class="span3">
                	<ul class="nav nav-tabs nav-stacked">
              		<li><a href="/settings/">Edit Profile</a></li>
              		<li class="active"><a href="/settings/security/">Edit Account</a></li>
            		</ul>
                </div>
                <div class="span9">
                          <p><a href="/settings/password_change/">Click here to change your password</a></p>
                            <hr/>
                          <h5><i class="icon-envelope"></i> Manage your email preferences</h5>
                          <form action="/settings/security/" method="post">
                            {% csrf_token %}
                            <div class="checkbox">
                              <label for="id_connection_request_email">
                                {{ form.connection_request_email }}
                                {{ form.connection_request_email.errors }}
                                Connection request email
                              </label>
                            </div>
                            <div class="checkbox">
                              <label for="id_endorsement_email">
                                {{ form.endorsement_email }}
                                {{ form.endorsement_email.errors }}
                                Endorsement email
                              </label>
                            </div>
                            <div class="checkbox">
                              <label for="id_profile_post_email">
                                {{ form.profile_post_email }}
                                {{ form.profile_post_email.errors }}
                                Profile post email
                              </label>
                            </div>
                            <div class="checkbox">
                              <label for="id_course_post_email">
                                {{ form.course_post_email }}
                                {{ form.course_post_email.errors }}
                                Course post email
                              </label>
                            </div>
                            <div class="checkbox">
                              <label for="id_new_course_member_email">
                                {{ form.new_course_member_email }}
                                {{ form.new_course_member_email.errors }}
                                New course member email
                              </label>
                            </div>
                            <div class="form-actions">
                                <input type="submit" class="btn" value="Save Changes" />
                            </div>
                          </form>
                </div>
            </div>
        </div>
    </div>
</div>          
{% endblock content %}

templates/website/activate_email_sent.html
{% extends "base.html" %}
{% block script %}
{% load static %}
{% endblock script %}
{% block style %}
<style type="text/css">
	body {
		background: #3399CC;
		background: -moz-radial-gradient(center, ellipse cover, #3399CC 0%, #2e5673 100%);
		background: -webkit-gradient(radial, center center, 0px, center center, 100%, color-stop(0%,#3399CC), color-stop(100%,#2e5673));
		background: -webkit-radial-gradient(center, ellipse cover, #3399CC 0%,#2e5673 100%);
		background: -o-radial-gradient(center, ellipse cover, #3399CC 0%,#2e5673 100%);
		background: -ms-radial-gradient(center, ellipse cover, #3399CC 0%,#2e5673 100%);
		background: radial-gradient(center, ellipse cover, #3399CC 0%,#2e5673 100%);
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3399CC', endColorstr='#2e5673',GradientType=1 );
		background-repeat: no-repeat;
		background-attachment: fixed;
	}
</style>
{% endblock style %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
	<div class="row">
    	<div class="span12" style="margin-top:15px; margin-bottom:40px;">
        	<div class="row">
    	<div class="span5 offset1">
        	<h1 style="color:#FFF; margin-top:150px;">Check your inbox.</h1>
        	<p style="color:#FFF;"><strong>We just sent you an activation link.</strong></p>
        </div>
        <div class="span5">
        	<img src="{% static "img/logo.png" %}" style="" />
        </div>
    </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/website/base_course.html
{% extends "base.html" %}
{% load static%}
{% block content %}
{% load widget_tweaks %}
    <div class="container">
    	<div class="row">
            <div class="span12"><!-- course container -->
            	<div class="row">
                	<div class="span3">
                    	<!-- course dash -->
                    	<div class="well" id="toolBar" style="padding:8px 0; margin-top:0px; border-right: 1px solid #E3E3E3; border-bottom:none; border-top:none; border-left:none; -webkit-border-radius: 0px; -moz-border-radius:0px; border-radius:0px; position:fixed; height:100%; width:217px;">
                        	<h5 class="coursesHeader" style="display:inline-block">Courses</h5>
                            	<ul class="nav nav-list" style="padding-bottom:30px;">
                                	<li class="divider"></li>
                              		{% for c in courses %}
                              		{% ifequal c.id current_course.id %}
                                	<i class="icon-caret-right" style="float:left; margin-top:2.5px; margin-right:4px;"></i>
                                	{% endifequal %}
                                		<li style="font-size:12px; font-weight:500; text-transform:uppercase;"><a href="/course/{{ c.id }}/">{{ c.number }}</a></li>
                              		{% endfor %}
                                    <li class="divider"></li>
                                    <a href="#addCourse" data-toggle="modal" class="btn btn-small" style="width:163px;"><i class="icon-plus-sign" style=""></i> Add Course</a>
                                </ul>
                        </div>
                        <!-- /course dash -->
                    </div>
                  	<div class="span9">
                    	<div class="row">
                        	<div class="span9" style="background-color:#F6F6F8; margin-bottom:0px;">
                              <div style="min-width:698px; width:698px; height:150px; border-left:1px solid #E2E3E4; border-right:1px solid #E2E3E4; padding-top:15px;">
                            	<div style="float:left; margin-left:20px;"> <!-- photo -->
                                    {% if image %}
                                    <img src="{{image.url}}" style="width:100px;" class="img-polaroid img-rounded"/>
                                    {% else %}
                                    <img src="{% static "img/course.png" %}" class="img-polaroid img-rounded"/>
                                    {% endif %}
                                </div>
                                <div style="float:left; width:420px; max-width:420px;">
                                    <p class="lead" style="font-size:24px; margin-bottom:0px; margin-left:15px; text-transform:uppercase;">{{ course_number }}</p>
                                    <p class="lead" style="font-size:18px; margin-bottom:5px; margin-left:15px;">{{ course_name }}</p>
                                    <p style="margin-left:15px; width: 420px; word-wrap: break-word;">Taught by {{ professor }}</p>
                                    <p  id="viewdetails" style="margin-left:15px; height:30px; width: 420px; word-wrap: break-word; ">{{ description }}<p>
                                </div>
                                <div style="float:right; margin-right:20px; width:120px;">
                                	{% if institution %}<p style="text-align:center;"><a href="#">{{ institution.title }}</a></p>{% endif %}
                                	<img src="{{institution.image.url}}" style="max-width:70px; margin-left:auto; margin-right:auto; display:block;" class="img-rounded"/>
                                </div>
                              </div>
                            </div>
                        </div>
                        <div class="row"> <!-- navigation -->
                                    <div class="span9">
                                        <div class="navbar">
                                          <div class="navbar-inner" style="padding-left:0; padding-right:0; border-radius:0px 0px 3px 3px; webkit-border-radius:0px 0px 3px 3px; moz-border-radius:0px 0px 3px 3px;">
                                            <ul class="nav">
                                              <li id="convo"><a href="/course/{{ course_id }}">Conversation</a></li>
                                              <li id="info"><a href="/course/{{ course_id }}/info">Info</a></li>
                                              <li id="docs"><a href="/course/{{ course_id }}/documents">Docs</a></li>
                                              <li id="events"><a href="/course/{{ course_id }}/events">Events</a></li>
                                              <li id="members"><a href="/course/{{ course_id }}/members">Members</a></li>
                                            </ul>
                                            <ul class="nav pull-right">
                                            <li class="divider-vertical"></li>
                                            <li class="dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="icon-cog"></b></a>
                                                <ul class="dropdown-menu">
                                                    <li><a href="/course/{{course_id}}/leave">Leave Course</a></li>
                                                </ul>
                                            </li>
                                            </ul>
                                          </div>
                                        </div>
                                    </div>
                				</div>
                        <div class="row">
                        {% block course_content %}
            			{% endblock course_content %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<div id="addCourse" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="addCourseLabel" aria-hidden="true">
  <form enctype="multipart/form-data" class="form-horizontal" method="post" action="/course/create/">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="addCourseLabel">Add one of your courses</h3>
    </div>
    <div class="modal-body">
      {% csrf_token %}
      <div class="control-group">
        <label class="control-label" for="id_course_number">Course Number</label>
        <div class="controls">
        {{course_form.course_number|attr:"autocomplete:off"|add_class:"addCourseAttr"}}
        <span class="help-block">Example: BIO201</span>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="id_course_id">Section Number</label>
        <div class="controls">
        {{course_form.course_id|attr:"autocomplete:off"|attr:"data-mask:9999"|add_class:"addCourseAttr"}}
        <span class="help-block">Example: 1000</span>
        </div>
      </div>             
    </div>
    <div class="modal-footer">
      <button type="submit" class="btn btn-inverse">Complete</button>
    </div>
  </form>
</div>
    <script>
$(function(){
	$(".coursedesExp").click(function(){
	var val = $(this).text();
	if (val == "More") {
    	$(".courseDescriptionExp").css('height', 'auto');
    	$(this).text("Less");
	} else {
    	$(".courseDescriptionExp").css('height', '80');
    	$(this).text("More");
	}
	return false;
});
});
$(function(){
	$(".evntdesExp").click(function(){
	var val = $(this).text();
	if (val == "More") {
    	$(".eventDescriptionExp").css('height', 'auto');
    	$(this).text("Less");
	} else {
    	$(".eventDescriptionExp").css('height', '20');
    	$(this).text("More");
	}
	return false;
});
});
</script>
{% endblock content %}

templates/website/reset.html
{% extends "base.html" %}
{% load static%}
{% block style%}
  <style type="text/css">
    body {background: #444444}
  </style>
{% endblock style %}
{% block script %}
  <script type="text/javascript">
    $('.dropdown-toggle').dropdown()
  </script>
  <script type="application/javascript">
    $(".collapse").collapse()
  </script>
  <script type="text/javascript">
    $(document).ready(function(){
    $("#picker1").birthdaypicker({});
    });
</script>
{% endblock script %}
{% block content %}
 <div class="container">
    <div class="row">
      <div class="span4 offset4">
        <h2 style="color:white; text-align:center; ">Retrieve Password</h2>
        <hr />
        </div>
    </div>
    <div class="row">
      <div class="span4 offset4">
          <form class="well">
              <label>Email:</label>
                <input type="text" class="input-small span3" style="width:95%; min-width:95%; max-width:95%;"  placeholder="">
                <p class="help-block">We'll send your password to your JMU email address.</p>
                <br />
                
                
                <a href="#" class="btn btn-primary" style="float:right;">Send Password</a>
                <br />
            </form>
        </div>
    </div>
  </div>
  {% endblock content %}